"use strict";

///////////////////////////////////////
// Modal window

//Elements
const header = document.querySelector(".header");

const modal = document.querySelector(".modal");
const overlay = document.querySelector(".overlay");
const btnCloseModal = document.querySelector(".btn--close-modal");
const btnsOpenModal = document.querySelectorAll(".btn--show-modal");

const buttonLearnMore = document.querySelector(".btn--scroll-to");
const section1 = document.querySelector("#section--1");
const section2 = document.querySelector("#section--2");
const section3 = document.querySelector("#section--3");

const navLinks = document.querySelectorAll(".nav__link");

//Registration modal
const openModal = function (e) {
  e.preventDefault();
  modal.classList.remove("hidden");
  overlay.classList.remove("hidden");
};

const closeModal = function () {
  modal.classList.add("hidden");
  overlay.classList.add("hidden");
};

btnsOpenModal.forEach((button) => button.addEventListener("click", openModal));

btnCloseModal.addEventListener("click", closeModal);
overlay.addEventListener("click", closeModal);

document.addEventListener("keydown", function (e) {
  if (e.key === "Escape" && !modal.classList.contains("hidden")) {
    closeModal();
  }
});

//Cookie message

const cookieMessage = document.createElement("div");
cookieMessage.classList.add("cookie-message");
cookieMessage.innerHTML =
  "We use cookies for better user experience <button class='btn btn--close--cookie'>Alright!</button>";

// header.prepend(cookieMessage);//First of parent element's inisde
// header.append(cookieMessage);//Last of parent element's inisde
// header.after(cookieMessage);//After the parent element
header.before(cookieMessage); //Before the paerent element

//Close cookie message
const btnCloseCookie = document.querySelector(".btn--close--cookie");

btnCloseCookie.addEventListener("click", () => {
  cookieMessage.remove();
});

//Smooth scrool
const scrollSmooth = function (btn, target) {
  btn.addEventListener("click", (e) => {
    e.preventDefault();
    target.scrollIntoView({ behavior: "smooth" });
  });
};

scrollSmooth(buttonLearnMore, section1);

//Other Solution

// scrollSmooth(navLinks[0], section1);
// scrollSmooth(navLinks[1], section2);
// scrollSmooth(navLinks[2], section3);

//Solution 2(Generated by Chatgpt)
navLinks.forEach((link) => {
  link.addEventListener("click", (event) => {
    event.preventDefault();
    const sectionId = event.target.getAttribute("href");
    const section = document.querySelector(sectionId);
    section.scrollIntoView({ behavior: "smooth" });
  });
});
